stages:
  data_ingestion:
    cmd: python src/image_authenticity_detector/pipeline/stage_01_data_ingestion.py
    deps:
      - src/image_authenticity_detector/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/real-vs-ai-generated/test
      - artifacts/data_ingestion/real-vs-ai-generated/train


  prepare_base_model:
    cmd: python src/image_authenticity_detector/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/image_authenticity_detector/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model



  training:
    cmd: python src/image_authenticity_detector/pipeline/stage_03_model_trainer.py
    deps:
      - src/image_authenticity_detector/pipeline/stage_03_model_trainer.py
      - src/image_authenticity_detector/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/real-vs-ai-generated/test
      - artifacts/prepare_base_model
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - LEARNING_RATE
    outs:
      - artifacts/training/model.h5


  

  evaluation:
    cmd: python src/image_authenticity_detector/pipeline/stage_04_model_evaluation.py
    deps:
      - src/image_authenticity_detector/pipeline/stage_04_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/real-vs-ai-generated/test
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false